// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi.Data;

#nullable disable

namespace webapi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webapi.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_address");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("AddressNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("address_number");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("country");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("postcode");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("street");

                    b.HasKey("AddressId");

                    b.ToTable("address");
                });

            modelBuilder.Entity("webapi.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_author");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Surname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("surname");

                    b.HasKey("AuthorId");

                    b.ToTable("author");
                });

            modelBuilder.Entity("webapi.Models.BillingAddress", b =>
                {
                    b.Property<int>("BillingAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_billing_address");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillingAddressId"));

                    b.Property<int>("AddressIdB")
                        .HasColumnType("int")
                        .HasColumnName("id_address");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("int")
                        .HasColumnName("id_user_type");

                    b.HasKey("BillingAddressId");

                    b.HasIndex("AddressIdB")
                        .IsUnique();

                    b.HasIndex("UserTypeId");

                    b.ToTable("billing_address");
                });

            modelBuilder.Entity("webapi.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_book");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("BookFormat")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("book_format");

                    b.Property<string>("BookLanguage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("book_language");

                    b.Property<string>("CoverImageURL")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("cover_image_url");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Genre")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("genre");

                    b.Property<int?>("NumberOfPages")
                        .HasColumnType("int")
                        .HasColumnName("number_of_pages");

                    b.Property<double>("Price")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("publication_date");

                    b.Property<string>("Publisher")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("publisher");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int")
                        .HasColumnName("quantity_in_stock");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("title");

                    b.HasKey("BookId");

                    b.ToTable("book");
                });

            modelBuilder.Entity("webapi.Models.Book_Author", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("AuthorOrder")
                        .HasColumnType("int")
                        .HasColumnName("author_order");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("books_authors");
                });

            modelBuilder.Entity("webapi.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_order");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<int>("BillingAddressIdO")
                        .HasColumnType("int")
                        .HasColumnName("id_billing_address");

                    b.Property<DateTime?>("DatePlaced")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_placed");

                    b.Property<string>("OrderDetails")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("order_details");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("order_status");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("order_type");

                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("id_payment_type");

                    b.Property<int>("ShippingAddressIdO")
                        .HasColumnType("int")
                        .HasColumnName("id_shipping_address");

                    b.Property<int>("ShippingTypeId")
                        .HasColumnType("int")
                        .HasColumnName("id_shipping_type");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("int")
                        .HasColumnName("id_user_type");

                    b.HasKey("OrderID");

                    b.HasIndex("BillingAddressIdO");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("ShippingAddressIdO");

                    b.HasIndex("ShippingTypeId");

                    b.HasIndex("UserTypeId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("webapi.Models.Order_Book", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("id_order");

                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("id_book");

                    b.Property<double>("BookPrice")
                        .HasColumnType("float")
                        .HasColumnName("book_price");

                    b.Property<int>("QuantityOrdered")
                        .HasColumnType("int")
                        .HasColumnName("quantity_ordered");

                    b.HasKey("OrderId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("Orders_Books");
                });

            modelBuilder.Entity("webapi.Models.PaymentType", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_payment");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<double>("AdditionalCost")
                        .HasColumnType("float")
                        .HasColumnName("additional_cost");

                    b.Property<string>("PaymentTypeVar")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("payment_type");

                    b.HasKey("PaymentId");

                    b.ToTable("PaymentType");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            AdditionalCost = 0.0,
                            PaymentTypeVar = "CardTransfer"
                        },
                        new
                        {
                            PaymentId = 2,
                            AdditionalCost = 1.5,
                            PaymentTypeVar = "CashOnDelivery"
                        });
                });

            modelBuilder.Entity("webapi.Models.PersonalInfo", b =>
                {
                    b.Property<int>("PersonalInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_personal_info");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonalInfoId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("surname");

                    b.HasKey("PersonalInfoId");

                    b.ToTable("personal_info");
                });

            modelBuilder.Entity("webapi.Models.ShippingAddress", b =>
                {
                    b.Property<int>("ShippingAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_shipping_address");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShippingAddressId"));

                    b.Property<int>("AddressIdS")
                        .HasColumnType("int")
                        .HasColumnName("id_address");

                    b.Property<string>("ShippingDetails")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("shipping_details");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("int")
                        .HasColumnName("id_user_type");

                    b.HasKey("ShippingAddressId");

                    b.HasIndex("AddressIdS")
                        .IsUnique();

                    b.HasIndex("UserTypeId");

                    b.ToTable("shipping_address");
                });

            modelBuilder.Entity("webapi.Models.ShippingType", b =>
                {
                    b.Property<int>("ShippingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_shipping");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShippingId"));

                    b.Property<double>("ShippingCost")
                        .HasColumnType("float")
                        .HasColumnName("shipping_cost");

                    b.Property<string>("ShippingTypeVar")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("shipping_type");

                    b.HasKey("ShippingId");

                    b.ToTable("ShippingType");

                    b.HasData(
                        new
                        {
                            ShippingId = 1,
                            ShippingCost = 4.9900000000000002,
                            ShippingTypeVar = "GLS"
                        },
                        new
                        {
                            ShippingId = 2,
                            ShippingCost = 4.4900000000000002,
                            ShippingTypeVar = "Post"
                        },
                        new
                        {
                            ShippingId = 3,
                            ShippingCost = 4.4900000000000002,
                            ShippingTypeVar = "SPS"
                        },
                        new
                        {
                            ShippingId = 4,
                            ShippingCost = 0.0,
                            ShippingTypeVar = "PersonalPickup"
                        });
                });

            modelBuilder.Entity("webapi.Models.TemporaryUser", b =>
                {
                    b.Property<int>("UserTypeIdTempUser")
                        .HasColumnType("int")
                        .HasColumnName("id_user_type");

                    b.Property<int>("PersonalInfoIdTempUser")
                        .HasColumnType("int")
                        .HasColumnName("id_personal_info");

                    b.HasKey("UserTypeIdTempUser");

                    b.HasIndex("PersonalInfoIdTempUser")
                        .IsUnique();

                    b.ToTable("temporary_user");
                });

            modelBuilder.Entity("webapi.Models.User", b =>
                {
                    b.Property<int>("UserTypeIdUser")
                        .HasColumnType("int")
                        .HasColumnName("id_user_type");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<int>("PersonalInfoIdUser")
                        .HasColumnType("int")
                        .HasColumnName("id_personal_info");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("profile_picture_url");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("role");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("UserTypeIdUser");

                    b.HasIndex("PersonalInfoIdUser")
                        .IsUnique();

                    b.ToTable("user");
                });

            modelBuilder.Entity("webapi.Models.UserType", b =>
                {
                    b.Property<int>("UserTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_user_type");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserTypeId"));

                    b.HasKey("UserTypeId");

                    b.ToTable("user_type");
                });

            modelBuilder.Entity("webapi.Models.BillingAddress", b =>
                {
                    b.HasOne("webapi.Models.Address", "Address")
                        .WithOne()
                        .HasForeignKey("webapi.Models.BillingAddress", "AddressIdB")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("webapi.Models.UserType", "UserType")
                        .WithMany("BillingAddresses")
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("webapi.Models.Book_Author", b =>
                {
                    b.HasOne("webapi.Models.Author", "Author")
                        .WithMany("Books_Authors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webapi.Models.Book", "Book")
                        .WithMany("BooksAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("webapi.Models.Order", b =>
                {
                    b.HasOne("webapi.Models.BillingAddress", "BillingAddress")
                        .WithMany("Orders")
                        .HasForeignKey("BillingAddressIdO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("webapi.Models.PaymentType", "PaymentType")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webapi.Models.ShippingAddress", "ShippingAddress")
                        .WithMany("Orders")
                        .HasForeignKey("ShippingAddressIdO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("webapi.Models.ShippingType", "ShippingType")
                        .WithMany("Orders")
                        .HasForeignKey("ShippingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webapi.Models.UserType", "UserType")
                        .WithMany("Orders")
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillingAddress");

                    b.Navigation("PaymentType");

                    b.Navigation("ShippingAddress");

                    b.Navigation("ShippingType");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("webapi.Models.Order_Book", b =>
                {
                    b.HasOne("webapi.Models.Book", "Book")
                        .WithMany("OrdersBooks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webapi.Models.Order", "Order")
                        .WithMany("OrdersBooks")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("webapi.Models.ShippingAddress", b =>
                {
                    b.HasOne("webapi.Models.Address", "Address")
                        .WithOne()
                        .HasForeignKey("webapi.Models.ShippingAddress", "AddressIdS")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("webapi.Models.UserType", "UserType")
                        .WithMany("ShippingAddresses")
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("webapi.Models.TemporaryUser", b =>
                {
                    b.HasOne("webapi.Models.PersonalInfo", "PersonalInfo")
                        .WithOne()
                        .HasForeignKey("webapi.Models.TemporaryUser", "PersonalInfoIdTempUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("webapi.Models.UserType", "UserType")
                        .WithOne()
                        .HasForeignKey("webapi.Models.TemporaryUser", "UserTypeIdTempUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PersonalInfo");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("webapi.Models.User", b =>
                {
                    b.HasOne("webapi.Models.PersonalInfo", "PersonalInfo")
                        .WithOne()
                        .HasForeignKey("webapi.Models.User", "PersonalInfoIdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("webapi.Models.UserType", "UserType")
                        .WithOne()
                        .HasForeignKey("webapi.Models.User", "UserTypeIdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PersonalInfo");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("webapi.Models.Author", b =>
                {
                    b.Navigation("Books_Authors");
                });

            modelBuilder.Entity("webapi.Models.BillingAddress", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("webapi.Models.Book", b =>
                {
                    b.Navigation("BooksAuthors");

                    b.Navigation("OrdersBooks");
                });

            modelBuilder.Entity("webapi.Models.Order", b =>
                {
                    b.Navigation("OrdersBooks");
                });

            modelBuilder.Entity("webapi.Models.PaymentType", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("webapi.Models.ShippingAddress", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("webapi.Models.ShippingType", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("webapi.Models.UserType", b =>
                {
                    b.Navigation("BillingAddresses");

                    b.Navigation("Orders");

                    b.Navigation("ShippingAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
